---
- name: aws_secret
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ensure ssh key file exists.
      file:
        path: "./ansible-dev.pem"
        mode: 0700
        state: touch

    - name: Install ssh key
      copy:
        content: "{{ lookup('amazon.aws.aws_secret', 'arn:aws:secretsmanager:us-east-2:605251984176:secret:ssh_key-Uq3zlG', region='us-east-2') }}"
        dest: "./ansible-dev.pem"
        mode: 0600

- name: ping host
  hosts: rhel
  gather_facts: no

  vars:
    - ansible_ssh_private_key_file: "./ansible-dev.pem"

  tasks:
    - name: ping
      ping:

- name: cleanup
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ensure ssh key file is cleaned up
      file:
        path: "./ansible-dev.pem"
        state: absent